DROP TABLE IF EXISTS COMP_RULE;
DROP SEQUENCE IF EXISTS COMPRULE_SEQUENCE;

CREATE TABLE IF NOT EXISTS COMP_RULE
(
	ID BIGINT NOT NULL PRIMARY KEY,
	KEY_WORDS VARCHAR2 NOT NULL,
	CHECK_TYPE BIGINT NOT NULL,
	EXCEPT_FIELDS VARCHAR2,
	GMT_CREATE TIMESTAMP NOT NULL
);

COMMENT ON COLUMN COMP_RULE.CHECK_TYPE IS '校验内容：1：校验请求是否发送；2：校验request信息；4：校验response信息；';

CREATE SEQUENCE IF NOT EXISTS COMPRULE_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE COMPRULE_SEQUENCE IS 'CONNECTION编号的序列';