DROP TABLE IF EXISTS COMPARE;
DROP SEQUENCE IF EXISTS COMP_SEQUENCE;
DROP INDEX IF EXISTS VERSION_ID_UNIQ_INDEX;

CREATE TABLE IF NOT EXISTS COMPARE
(
	ID BIGINT NOT NULL PRIMARY KEY, 
	VERSION_ID BIGINT NOT NULL,
	COMT_ID_MAIN BIGINT NOT NULL,
	COMT_ID_CHECKED BIGINT NOT NULL,
	MAIN_ENVRMT BIGINT NOT NULL,
	CHECKED_ENVRMT BIGINT NOT NULL,
	SAME_ID VARCHAR2,
	IS_CHECK INT,
	IS_PASS INT,
	FEATURES VARCHAR2,
	GMT_CREATE TIMESTAMP NOT NULL
);

COMMENT ON COLUMN COMPARE.VERSION_ID IS '运行的版本ID';
COMMENT ON COLUMN COMPARE.COMT_ID_MAIN IS '标准、正确的http信息所对应的ID';
COMMENT ON COLUMN COMPARE.MAIN_ENVRMT IS '标准、正确的参考环境，0：线上；1：beta；2：预发；3：灰度预发；4：beta1；5：beta2；6：灰度线上';
COMMENT ON COLUMN COMPARE.COMT_ID_CHECKED IS '待校验的http信息所对应的ID';
COMMENT ON COLUMN COMPARE.CHECKED_ENVRMT IS '待校验的环境，0：线上；1：beta；2：预发；3：灰度预发；4：beta1；5：beta2；6：灰度线上';
COMMENT ON COLUMN COMPARE.SAME_ID IS '相同的请求、宝贝ID等能唯一代表该url';
COMMENT ON COLUMN COMPARE.IS_CHECK IS '默认为false，当两个环境对比完成后，改变值为true';
COMMENT ON COLUMN COMPARE.FEATURES IS '记录额外的host绑定, k:v形式，host:1，表示有额外的绑定';


CREATE SEQUENCE IF NOT EXISTS COMP_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE COMP_SEQUENCE IS 'COMPARE编号的序列';
