DROP TABLE IF EXISTS COMPARE;
DROP SEQUENCE IF EXISTS COMP_SEQUENCE;
DROP INDEX IF EXISTS COMP_TRADE_UNIQ_INDEX;

CREATE TABLE IF NOT EXISTS COMPARE
(
	ID BIGINT NOT NULL PRIMARY KEY, 
	SAME_ID VARCHAR2 NOT NULL,
	COMT_ID_MAIN VARCHAR2 NOT NULL,
	MAIN_ENVRMT BIGINT NOT NULL,
	COMT_ID_CHECKED VARCHAR2 NOT NULL,
	CHECKED_ENVRMT BIGINT NOT NULL,
	CAMP_RULES VARCHAR2 NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL
);

COMMENT ON COLUMN COMPARE.COMT_ID_MAIN IS '标准、正确的http信息';
COMMENT ON COLUMN COMPARE.MAIN_ENVRMT IS '标准、正确的参考环境，0：线上；1：beta；2：预发；3：灰度预发；4：beta1；5：beta2；6：灰度线上';
COMMENT ON COLUMN COMPARE.COMT_ID_CHECKED IS '待校验的http信息';
COMMENT ON COLUMN COMPARE.CHECKED_ENVRMT IS '待校验的环境，0：线上；1：beta；2：预发；3：灰度预发；4：beta1；5：beta2；6：灰度线上';
COMMENT ON COLUMN COMPARE.CAMP_RULES IS '对比规则';

CREATE SEQUENCE IF NOT EXISTS COMP_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE COMP_SEQUENCE IS 'COMPARE编号的序列';