DROP TABLE IF EXISTS COMMUNICATION;
DROP SEQUENCE IF EXISTS COMT_SEQUENCE;
DROP INDEX IF EXISTS COMT_TRADE_UNIQ_INDEX;

CREATE TABLE IF NOT EXISTS COMMUNICATION
(
	ID BIGINT NOT NULL PRIMARY KEY,
	TRACE_ID VARCHAR2 NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS COMT_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE COMT_SEQUENCE IS 'COMMUNICATION±àºÅµÄÐòÁÐ';

CREATE UNIQUE HASH INDEX IF NOT EXISTS COMT_TRADE_UNIQ_INDEX ON COMMUNICATION(TRACE_ID);