DROP TABLE IF EXISTS HTTP_CONNECTION;
DROP SEQUENCE IF EXISTS HCONNECTION_SEQUENCE;

CREATE TABLE IF NOT EXISTS HTTP_CONNECTION
(
	ID BIGINT NOT NULL PRIMARY KEY,
	URL VARCHAR2 NOT NULL,
	REQ_DATA_NASID BIGINT NOT NULL,
	RES_DATA_NASID BIGINT NOT NULL,
	SERVER_IP VARCHAR2,
	COMT_ID BIGINT NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS HCONNECTION_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE HCONNECTION_SEQUENCE IS 'CONNECTION±àºÅµÄÐòÁÐ';