DROP TABLE IF EXISTS FILTER;
DROP SEQUENCE IF EXISTS FILTER_SEQUENCE;

CREATE TABLE IF NOT EXISTS FILTER
(
	ID BIGINT NOT NULL PRIMARY KEY,
	REQ_URL VARCHAR2 NOT NULL,
	FILTER_KEY VARCHAR2,
	FILTER_VALUE_NASID BIGINT,
	FILTER_VALUE VARCHAR2,
	OPERATE INT NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL
);

COMMENT ON TABLE FILTER IS 'FILTER存储';
COMMENT ON COLUMN FILTER.ID IS 'FILTER编号';
COMMENT ON COLUMN FILTER.REQ_URL IS '请求url';
COMMENT ON COLUMN FILTER.FILTER_KEY IS '过滤器的key，key为null时，全部替换';
COMMENT ON COLUMN FILTER.FILTER_VALUE_NASID IS 'key为null时，用NAS存储数据；key不为空时，FILTER_VALUE_NASID为null';
COMMENT ON COLUMN FILTER.FILTER_VALUE IS '新的value值，filter_value为空的时候，删除或设置为空';
COMMENT ON COLUMN FILTER.OPERATE IS '0:增加，1：删除，2：修改';

CREATE SEQUENCE IF NOT EXISTS FILTER_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;

DROP TABLE IF EXISTS FILTERS;
DROP SEQUENCE IF EXISTS FILTERS_SEQUENCE;

CREATE TABLE IF NOT EXISTS FILTERS
(
	ID BIGINT NOT NULL PRIMARY KEY,
	FILTER_IDS VARCHAR2 NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL
);

COMMENT ON TABLE FILTERS IS 'FILTERS存储';
COMMENT ON COLUMN FILTERS.FILTER_IDS IS '过滤器filter的id，以分号隔开';

CREATE SEQUENCE IF NOT EXISTS FILTERS_SEQUENCE START WITH 100 INCREMENT BY 1 CACHE 1;

