DROP TABLE IF EXISTS NAS;
DROP SEQUENCE IF EXISTS NAS_SEQUENCE;
DROP INDEX IF EXISTS IDX_NAS_BATCH;

CREATE TABLE IF NOT EXISTS NAS 
(
	ID BIGINT NOT NULL PRIMARY KEY,
	BATCH_NO VARCHAR2 NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL,
	FEATURES VARCHAR2 NOT NULL,
	CONTENT BLOB NOT NULL
);

COMMENT ON TABLE NAS IS 'NAS存储';
COMMENT ON COLUMN NAS.ID IS '存储编号';
COMMENT ON COLUMN NAS.BATCH_NO IS '上传批号';
COMMENT ON COLUMN NAS.GMT_CREATE IS '创建时间';
COMMENT ON COLUMN NAS.CONTENT IS '内容';

CREATE SEQUENCE IF NOT EXISTS NAS_SEQUENCE START WITH 10000 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE NAS_SEQUENCE IS 'NAS存储编号索引';

CREATE HASH INDEX IDX_NAS_BATCH ON NAS(BATCH_NO);

