DROP TABLE IF EXISTS VERSION;
DROP SEQUENCE IF EXISTS VERSION_SEQUENCE;

CREATE TABLE IF NOT EXISTS VERSION
(
	ID BIGINT NOT NULL PRIMARY KEY, 
	RULE_IDS VARCHAR2 NOT NULL,
	GMT_CREATE TIMESTAMP NOT NULL
);

COMMENT ON COLUMN VERSION.RULE_IDS IS '对比规则ID的集合，用逗号隔开';


CREATE SEQUENCE IF NOT EXISTS VERSION_SEQUENCE START WITH 1 INCREMENT BY 1 CACHE 1;
COMMENT ON SEQUENCE VERSION_SEQUENCE IS 'VERSION编号的序列';